name: Publish Docker Containers
on:
  workflow_call:
    inputs:
      base_tag:
        type: string
        required: false
      extra_tag:
        type: string
        required: false
      registry:
        type: string
        default: ghcr.io
      image_name:
        type: string
        default: ${{ github.repository }}

env:
  REGISTRY: ${{ inputs.registry }}
  IMAGE_NAME: ${{ inputs.image_name }}

jobs:
  build_and_publish_docker:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.version }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version
        id: version
        run: |
          VERSION=$(sed "s/a/-a./" <<< $(python setup.py --version))
          echo ::set-output name=version::${VERSION}
        env:
          image_name: ${{ env.IMAGE_NAME }}

      - name: Extract metadata for base Docker
        id: base_meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.version.outputs.version }}
            type=ref,event=branch
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.base_meta.outputs.tags }}
          labels: ${{ steps.base_meta.outputs.labels }}
          target: ${{ inputs.base_tag }}

      - name: Extract metadata for extra Docker
        if: "${{ inputs.extra_tag != '' }}"
        id: extra_meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ inputs.extra_tag }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.version.outputs.version }}
            type=ref,event=branch
      - name: Build and push extra Docker image
        if: "${{ inputs.extra_tag != '' }}"
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.extra_meta.outputs.tags }}
          labels: ${{ steps.extra_meta.outputs.labels }}
          target: ${{ inputs.extra_tag }}
